users = [
    {
        'email' : 'danblack@msn.com',
        'first_name': 'Dan',
        'last_name': 'Black',
        'gender': 1,
        'age': 27,
        'description': "I live with a really cute puppy, but I'm trying to get by on Tinder without his help.",
        'last_seen_lat': 56.171089,
        'last_seen_long': 10.189372,
        'looking_for': [0, 2],
        'age_from': 22,
        'age_to': 29,
        'search_radius': 50,
        'photo_path': '/dan_black/',
        'photo0': '0.jpg',
        'photo1': '1.jpg',
        'photo2': '2.jpg',
        'photo3': '3.jpg',
        'photo4': '4.jpg',
        'photo5': '5.jpg'
    },
    {
        'email' : 'thomaswhite@msn.com',
        'first_name': 'Thomas',
        'last_name': 'White',
        'gender': 1,
        'age': 20,
        'description': "Uconn\nLove Music\nLove the Outdoors\nLove life.\nLet's go for a hike sometime.",
        'last_seen_lat': 56.171089,
        'last_seen_long': 10.189372,
        'looking_for': [2],
        'age_from': 18,
        'age_to': 25,
        'search_radius': 75,
        'photo_path': '/thomas_white/',
        'photo0': '0.jpg',
        'photo1': '1.jpg',
        'photo2': '2.jpg',
        'photo3': '3.jpg',
        'photo4': '4.jpg'
    },
    # { user/test_user_images/
    #     'email' : '',
    #     'first_name': '',
    #     'last_name': '',
    #     'gender': 1,
    #     'age': 27,
    #     'description': '',
    #     'last_seen_lat': 0.0,
    #     'last_seen_long': 0.0,
    #     'looking_for': [0, 1, 2],
    #     'age_from': 18,
    #     'age_to': 30,
    #     'search_radius': 805,
    #     'photo0': ''
    # }
]